"""empty message

Revision ID: 76e421606310
Revises: be3d3ff78d1b
Create Date: 2021-02-28 15:23:28.783187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76e421606310'
down_revision = 'be3d3ff78d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'Age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
