"""empty message

Revision ID: 8f82a7b4e2d7
Revises: 76e421606310
Create Date: 2021-02-28 15:23:53.224555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f82a7b4e2d7'
down_revision = '76e421606310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=1280), nullable=False),
    sa.Column('rol', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.drop_index('Email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=1280), nullable=False),
    sa.Column('rol', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('Email', 'users', ['Email'], unique=True)
    op.drop_table('USERS')
    # ### end Alembic commands ###
