"""empty message

Revision ID: d389d79278cd
Revises: 
Create Date: 2021-02-25 23:46:23.246406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd389d79278cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=1280), nullable=False),
    sa.Column('rol', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
